level_3
MihailR1/typing_challenges pull request #3
Opened 2023-11-21 05:32 UTC by MihailR1

Упражнения 3го уровня

2023-11-21 05:34 UTC, MihailR1 commented on level_3/2.py
> +def calculate_total_spent_for_user(user: TypedDict[str, str | int | list[int]]) -> int:
Аннотацию для значений словаря, тут можно как Any использовать или лучше как расписал в файле?

2023-11-21 05:39 UTC, MihailR1 commented on level_3/1.py
>      # попробуйте использовать typing.Mapping: transactions_amounts_map по смыслу не должен меняться внутри функции
А в каких случаях Mapping используется? Насколько понял, когда есть собственный класс с реализованным методом __getitem__ или может в каких-то еще случаях используется?

2023-11-21 21:05 UTC, khoshov commented on level_3/2.py
> +def calculate_total_spent_for_user(user: TypedDict[str, str | int | list[int]]) -> int:
Я бы сделал так

```python
class User(TypedDict):
    name: str
    age: int
    transactions_sums: list[int]


def calculate_total_spent_for_user(user: User) -> int:
    # попробуй тут воспользовать typing.TypedDict
    pass
```

2023-11-21 21:10 UTC, khoshov commented on level_3/1.py
>      # попробуйте использовать typing.Mapping: transactions_amounts_map по смыслу не должен меняться внутри функции
С таймингом

https://youtu.be/yG24c0tgaXs?si=e3opV7PTz46bL94F&t=772

2023-11-21 21:10 UTC, khoshov requested changes
Требует доработки

2023-11-22 04:00 UTC, MihailR1 commented on level_3/2.py
> +def calculate_total_spent_for_user(user: TypedDict[str, str | int | list[int]]) -> int:
> Я бы сделал так
> 
> ```python
> class User(TypedDict):
>     name: str
>     age: int
>     transactions_sums: list[int]
> 
> 
> def calculate_total_spent_for_user(user: User) -> int:
>     # попробуй тут воспользовать typing.TypedDict
>     pass
> ```

только ради аннотации создавать класс?

2023-11-25 21:05 UTC, khoshov approved these changes
LGTM

2023-11-26 07:06 UTC, merged